### ISSUE TITLE
Should newlines be translated?

### ISSUE THREAD

**Issue by sergiuiacob1** [gabrielpacheco23/google-translator#2]
If you translate a text that contains a newline, the translation will return a "\n" instead of the actual new line.

For example, translation from Romanian to English:
"Salut!
Ce faci?"
Translates to:
"Hello!\nWhat are you doing?"

I'm not sure if this is how this should work :D

**Comment by gabrielpacheco23** [comment]
Updated. Test it and if the error continues please let me know.

**Comment by sergiuiacob1** [comment]
Nice! There's also something that you should take care of, I think.
At line 74: `var data = await http.get(url);`
You should test `if (data.statusCode != 200) return null;`. In case the request fails (response code is not 200, which is OK), you should return a null translation.

**Comment by gabrielpacheco23** [comment]
Did it. Thanks for the advice! I'm going to make better changes later. Indeed sometimes requests to old Google Translate API fails and this can be a real problem.
