### ISSUE TITLE
Is there any way to detect language?

### ISSUE THREAD

**Issue by AmanStreak** [gabrielpacheco23/google-translator#22]

**Comment by kaungkhanthtun** [comment]
you can omit from language and it'll auto-detect the language of the source text

translator.translate("Hello", to: 'es').then(print);
// prints Hola

**Comment by svonidze** [comment]
> Is there any way to detect language?
not in this library. Google Translator can auto-detect language of passed text as @K2H-Giant mentioned
```
translator.translate("Hello", to: 'es').then(print);
prints Hola
```
However often Google Translator does this detection incorrectly. 

There is a good library for detection text language https://github.com/wooorm/franc and ports to some programming languages but not Dart. You may be inspired by that library code to solve your particular problem.
