### ISSUE TITLE
CORS policy blocking request

### ISSUE THREAD

**Issue by diegoflassa** [gabrielpacheco23/google-translator#25]
I´m having this issue when running from a flutter web app:

Access to XMLHttpRequest at 'https://translate.googleapis.com/translate_a/single?client=t&sl=auto&tl=af&hl=af&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&tk=586426.967108&q=my_text_to_translate from origin 'https://theheroesbook.web.app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Failed to load resource: net::ERR_FAILED

**Comment by houdayec** [comment]
You have to update your CORS policy on your server side to allow your server interacting with Google ones. It does not depend from the package.

**Comment by gabrielpacheco23** [comment]
> You have to update your CORS policy on your server side to allow your server interacting with Google ones. It does not depend on the package.

As @houdayec said, you have to set your CORS headers up.

**Comment by diegoflassa** [comment]
Thanks fro the answers! Its fixed !

**Comment by tanjunior** [comment]
> You have to update your CORS policy on your server side to allow your server interacting with Google ones. It does not depend on the package.

What server side? I am getting this error on `flutter run` web
