### ISSUE TITLE
Language not support

### ISSUE THREAD

**Issue by faysalneowaz** [gabrielpacheco23/google-translator#29]
E/flutter (29821): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: RangeError (index): Invalid value: Valid value range is empty: 0
E/flutter (29821): #0      List.[] (dart:core-patch/growable_array.dart:177:60)
E/flutter (29821): #1      _InputScreenState.parseTheText (package:restaurant_app/input.dart:176:48)
E/flutter (29821): <asynchronous suspension>
E/flutter (29821): #2      _InputScreenState.build.<anonymous closure> (package:restaurant_app/input.dart:351:27)
E/flutter (29821): #3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter (29821): #4      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter (29821): #5      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter (29821): #6      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
E/flutter (29821): #7      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
E/flutter (29821): #8      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
E/flutter (29821): #9      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter (29821): #10     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (29821): #11     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter (29821): #12     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter (29821): #13     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358:19)
E/flutter (29821): #14     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter (29821): #15     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter (29821): #16     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter (29821): #17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter (29821): #18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter (29821): #19     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (29821): #20     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (29821): #21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (29821): #22     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (29821): #23     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
E/flutter (29821): 

This is happened when I am going convert English to 

Chinese | zh
-- | --
Chinese (Simplified) | zh-Hans
Chinese (Traditional) | zh-Hant
Chuvash | cv

**Comment by faysalneowaz** [comment]
I need help can any one help me with this? is there any other solution?

**Comment by gabrielpacheco23** [comment]
The only chinese languages supported by Google Translate are zh-CN (Simplified), and zh-TW (Tradicional).

**Comment by gabrielpacheco23** [comment]
Merged @ji3g4m6zo6 PR.
