### ISSUE TITLE
Every time it print two times

### ISSUE THREAD

**Issue by Tushargupta9800** [gabrielpacheco23/google-translator#31]
I just copy paste the code written in the Example but when I run the code It translate the Language but it print two times the same String.
The Code:
```
String input = "Dashboard";
    await translator
        .translate(input, to: 'ar')
        .then((result) => print("$input : $result"));
```

But I want it print only single time So, whats the error???

**Comment by gabrielpacheco23** [comment]
You are using "await" and "then(...)" in the same sentence, causing it to print the string twice.
