### ISSUE TITLE
Http dependency

### ISSUE THREAD

**Issue by jefioliveira** [gabrielpacheco23/google-translator#4]
would you know how to solve dependency?

Because translator >=0.1.0+5 depends on http from hosted and depends on http from git, translator >=0.1.0+5 is forbidden.
So, because depends on translator ^0.1.0+5, version solving failed.
Unable to reload your application because "flutter packages get" failed to update package dependencies.

**Comment by gabrielpacheco23** [comment]
> would you know how to solve dependency?
> 
> Because translator >=0.1.0+5 depends on http from hosted and depends on http from git, translator >=0.1.0+5 is forbidden.
> So, because depends on translator ^0.1.0+5, version solving failed.
> Unable to reload your application because "flutter packages get" failed to update package dependencies.

Did you do `flutter packages get` or just `pub get`? Also, if you're using VS Code, run `flutter packages get` on a terminal instead of VS Code automatic "pub get" when saving pubspec.yaml file.
