### ISSUE TITLE
Class 'String' has no instance method '<<'. Error

### ISSUE THREAD

**Issue by salahturkmen** [gabrielpacheco23/google-translator#41]
E/flutter (12356): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: NoSuchMethodError: Class 'String' has no instance method '<<'.
E/flutter (12356): Receiver: "406398"
E/flutter (12356): Tried calling: <<(3)
E/flutter (12356): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
E/flutter (12356): #1      GoogleTokenGenerator.wr (package:translator/src/tokens/google_token_gen.dart:80:60)
E/flutter (12356): #2      GoogleTokenGenerator.tokenGen (package:translator/src/tokens/google_token_gen.dart:58:9)
E/flutter (12356): #3      GoogleTokenGenerator.generateToken (package:translator/src/tokens/google_token_gen.dart:14:12)
E/flutter (12356): #4      GoogleTranslator.translate (package:translator/src/google_translator.dart:46:28)

**Comment by salahturkmen** [comment]
Anyone Here￼￼?

**Comment by Chandram-Dutta** [comment]
Hey I am receiving similar issue...any solution??

**Comment by Sasha071201** [comment]
I have the same problem: Class 'String' has no instance method '<<'.

**Comment by Chandram-Dutta** [comment]
> I have the same problem: Class 'String' has no instance method '<<'.

Its an issue with Bloc library... Idk why but the Issue resolved when I used riverpod

**Comment by MohaAmiry** [comment]
any solutions?? i'm facing the same error.
