### ISSUE TITLE
Chinese iSO code is wrong

### ISSUE THREAD

**Issue by fdchiu** [gabrielpacheco23/google-translator#52]
The current package uses 'zh-Hans' for Chinese simplified and 'zh-Hant' for traditional Chinese. They should really be:
'zh-cn' and 'zh-tw' respectively.  'zh-Hans' and 'zh-Hant' are NOT supported by google translate.

**Comment by raphaeldelio** [comment]
The codes for Chinese Simplified and Chinese Traditional are respectively 'zh-cn' and 'zh-tw'.

You can see these references in: https://github.com/gabrielpacheco23/google-translator/blob/master/lib/src/langs/language.dart

Closing issue.
