### ISSUE TITLE
Change The Language Code for Punjabi

### ISSUE THREAD

**Issue by Jagrajsinghji** [gabrielpacheco23/google-translator#7]
I have been checking this package and it was not translating to the Punjabi Language. I have checked the languages.dart file and I came to know that the language code for Punjabi(Line Number 77 in file) is different from the one documented in [https://cloud.google.com/translate/docs/languages](url). I have locally changed it and it worked. Could you please change it in the package?
Thanks in advance!

**Comment by gabrielpacheco23** [comment]
Updated! Thanks.
