### ISSUE TITLE
   'iw': 'Hebrew'- right,     'he': 'Hebrew' - wrong

### ISSUE THREAD

**Issue by Yang321423** [gabrielpacheco23/google-translator#76]
This package is really great. Thank you for making it. However, I found an error.
There is an error in class LanguageList. The Google language code for Hebrew is 'iw' not 'he'. So I am currently getting an error when translating Hebrew. Please fix it.
I think there might be more this kind of errors.  I haven't checked all the other language codes to see if there are any errors.

**Comment by gabrielpacheco23** [comment]
Fixed. Sorry for the late response.
